### ISSUE TITLE
Dependencies on GNU/Linux for LAC

### ISSUE THREAD

**Issue by ghost** [libertyernie/LoopingAudioConverter#8] opened 2017-06-07 14:57 UTC
Hello. I am trying to get Looping Audio Converter (LAC) not crashing on my Trisquel (Ubuntu-based) distro, and I have been hatching away at some dependency issues.

I needed to make sure libso, libvorbis and mono-complete were installed, however I am still having an issue where it seems some Mono related dependencies are missing on my machine.

Here is part of the error I am seeing:

```
[xcb] Too much data requested from _XRead
[xcb] This is most likely caused by a broken X extension library
[xcb] Aborting, sorry about that.
```

Do you need any more information in order to know what this issue may be and how to fix it?

I really, really love this program and have found it very useful is helping me convert lots of VGMs and VGZ files I have into FLACs. I have not found a program that is more easy to use. The problem is, I am a GNU/Linux user and would like to reap the benefits of your software on my main computer.

Please advise.

Regards,

David

**Comment by libertyernie** [comment] 2017-06-07 15:24
Whatever the problem is, there are probably other Mono applications where it happens too. It seems like it would have something to do with the GUI side of things.

I also tried installing 32-bit mono-complete on a 64-bit Ubuntu 16.10, but it doesn't look like you can do that.

**Comment by libertyernie** [comment] 2017-06-07 15:29
Try running it with the environment variable MONO_WINFORMS_XIM_STYLE=disabled.

I also found another bug in the RSTM encoding (trying to use memset and can't find it) so I'll see if I can get that fixed.

**Comment by libertyernie** [comment] 2017-06-07 19:50
1.4.1rc1 contains the RSTM fix.

**Comment by davidpgil** [comment] 2017-06-07 21:11
While we are at reporting off-topic bugs, I noticed that vgm2wav and vgmstream are not found on GNU/Linux configuration file, so I needed to set an absolute path instead of relative path for some reason.

**Comment by davidpgil** [comment] 2017-06-08 01:38
... While we are at reporting off-topic bugs, I noticed that in the "LoopingAudioConverter.exe.config" file, vgm2wav and vgmstream are not auotmatically found when running LAC via double-clicking the app, so I needed to set an absolute path instead of relative path. I dont know why, but this works...

```
...
    <add key="vgm2wav_path" value="/home/johndoe/Desktop/LAC/tools/vgm2wav/vgm2wav" />
    <add key="vgmstream_path" value="/home/johndoe/Desktop/LAC/tools/vgmstream/vgmstream" />
...
```

**Comment by libertyernie** [comment] 2017-08-24 13:15
It could have something to do with your current working directory being different from the folder the .exe is in. Maybe I can work around that.

**Comment by libertyernie** [comment] 2024-05-22 18:48
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.

**Closed by libertyernie** 2024-05-22 18:48 UTC
