### ISSUE TITLE
[Feature Request] Nus3Bank

### ISSUE THREAD

**Issue by AngelSora** [libertyernie/LoopingAudioConverter#11] opened 2017-07-27 21:50 UTC
I have one last request, Sm4sh modding is using for music and sound a Nus3bank format. Sure i can easily use the tool i need to do this but its too long and the ending loop always do a crackled sound. Your tool is so well organized so i really need this format to work with also a fixed end loop. You can check the Easy Nus3bank Editor With GUI to see what i mean. Nus3bank can be read with VGMStream (an add-on for foobar2000).

**Comment by libertyernie** [comment] 2017-07-28 15:12
The tricky thing about nus3bank is that each file can have more than one track/song in it. Looping Audio Converter was designed to use formats where 1 file = 1 track. This is also the reason that formats like .nsf and .gbs aren't supported for input, but .vgm is.

That said, version 2.0.0 allows IDSP as an output format. Easy Nus3bank Editor can import .idsp files, right? That might be a good way to do it.

**Comment by AngelSora** [comment] 2017-07-29 17:22
Okay, i see what i can do with it. Thanks for your help.

**Comment by libertyernie** [comment] 2024-05-22 18:48
I'm closing any issues more than a year old. If you're still having a persistent issue with the newest version of Looping Audio Converter, please file a new issue on this GitHub repository instead of replying to this one. Make sure to include the exact wording of any error you're getting, which settings you're using when converting audio (if applicable), and - if possible - a link to the file you're using as input.

**Closed by libertyernie** 2024-05-22 18:48 UTC
